float32 length      # in m, length of the segment
float32 width       # in m, width of the segment
float32 radius      # in m, radius of the segment
float32 angle       # in rad, angle of the segment
sam_msgs_package/MapObject[] objects  # objects on the segment
float32 start_x     # x coordinate of the start point in m
float32 start_y     # y coordinate of the start point in m
float32 start_angle # angle of the start point in rad